name: CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build --parallel

  slackNotification:
    needs: build
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification SUCCESSFUL
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_COLOR: '#4CAF50'
          SLACK_ICON: https://www.seekicon.com/free-icon-download/ci-icon_2.svg
          SLACK_TITLE: SUCCESSFUL
          SLACK_USERNAME: CI
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - name: Slack Notification FAILED
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_COLOR: '#F44336'
          SLACK_ICON: https://www.seekicon.com/free-icon-download/ci-icon_2.svg
          SLACK_TITLE: FAILED
          SLACK_USERNAME: CI
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}